name: Enforce Branch Name

on:
  push:
    branches:
      - "*"

jobs:
  enforce_branch_name:
    runs-on: "k8s-native"
    container:
      image: "ubuntu:24.04"

    steps:
      - name: Check Branch Name
        shell: bash
        run: |
          regular_branch_pattern='^DEV-([0-9]{3,}|nojira).*$'
          hotfix_branch_pattern='^HF-.*$'
          branch_name=$(echo $GITHUB_REF | sed 's/refs\/heads\///')
          if [[ ! $branch_name =~ $regular_branch_pattern && ! $branch_name =~ $hotfix_branch_pattern ]]; then
            echo "Branch name $branch_name does not match the required patterns."
            exit 1
          fi
